In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import re
import os
import glob

# display settings
pd.set_option('display.max_columns', None)

In [10]:
folder_path = "../data/1_bronze_raw/munis=city_of_tshwane/city=akasia/type=rent"
file_name = "11007_20260202_171247.parquet"
file_path = os.path.join(folder_path, file_name)

df = pd.read_parquet(file_path)

In [11]:
df

,listing_number,scrape_at,listing_data
0,108782207,2026-02-02T17:12:43.899176,"<div class=""p24_tileContainer js_resultTile Se..."
1,116872499,2026-02-02T17:12:43.899994,"<div class=""SeoulForecast js_resultTile p24_ti..."
2,116702498,2026-02-02T17:12:43.900691,"<div class=""SeoulLiberal js_resultTile p24_til..."
3,116850269,2026-02-02T17:12:43.901314,"<div class=""SeoulSaddest js_resultTile p24_til..."
4,116794164,2026-02-02T17:12:43.901769,"<div class=""SeoulYankee js_resultTile p24_tile..."
5,115999979,2026-02-02T17:12:43.902314,"<div class=""SeoulRobe js_resultTile p24_tileCo..."
6,116833744,2026-02-02T17:12:43.902922,"<div class=""SeoulGetting js_resultTile p24_til..."
7,116850243,2026-02-02T17:12:43.903554,"<div class=""SeoulPalette js_resultTile p24_til..."
8,116735719,2026-02-02T17:12:43.904037,"<div class=""SeoulConcord js_resultTile p24_til..."

In [12]:
lookup = pd.read_parquet("../data/0_metadata/suburb_lookup.parquet")
lookup

,suburb_id,suburb_name,city_id,city_name,province_id,province_name,municipality,last_scraped
0,3990,amandasig,2462,akasia,1,gauteng,City of Tshwane,2026-02-02
1,4002,chantelle,2462,akasia,1,gauteng,City of Tshwane,2026-02-02
2,4012,clarina,2462,akasia,1,gauteng,City of Tshwane,2026-02-02
3,4102,doreg ah,2462,akasia,1,gauteng,City of Tshwane,2026-02-02
4,429,eldorette,2462,akasia,1,gauteng,City of Tshwane,2026-02-02
...,...,...,...,...,...,...,...,...
2068,346,rooiwal ah,2473,wonderboom,1,gauteng,City of Tshwane,2026-02-06
2069,347,vasfontein ah,2473,wonderboom,1,gauteng,City of Tshwane,2026-02-06
2070,17,walmansthal ah,2473,wonderboom,1,gauteng,City of Tshwane,2026-02-06
2071,55,waterval ah,2473,wonderboom,1,gauteng,City of Tshwane,None
2072,51,welgevonden,2473,wonderboom,1,gauteng,City of Tshwane,None

In [13]:
suburb_id = file_name.split('_')[0]
suburb, city, munis = lookup.loc[lookup['suburb_id'] == suburb_id, ['suburb_name', 'city_name', 'municipality']].values[0]

In [14]:
print(suburb, city, munis)

heatherview akasia City of Tshwane

In [7]:
BeautifulSoup(df["listing_data"][0], "html.parser")

<div class="CrammerLaybys js_resultTile p24_tileContainer" data-listing-number="116872112">
<div class="p24_regularTile js_rollover_container js_resultTileClickable p24_tileHoverWrapper" data-listing-number="116872112" itemscope="" itemtype="http://schema.org/Product">
<meta content="2 Bedroom Apartment" itemprop="name"/>
<div class="" title="2 Bedroom Apartment / flat to rent in Buffelsdrift AH - Pretoria">
<span class="js_listingTileImageHolder p24_image">
<a href="/to-rent/buffelsdrift-ah/pretoria/gauteng/1/116872112">
<img alt="This unit is on the 1st Floor of Oscars Place which is situated in the Paramount Estate Tygerpoort Pretoria East.  Easy access to ..." class="js_rollover_target js_rollover_default js_P24_listingImage js_lazyLoadImage" height="212" itemprop="image" src="https://images.prop24.com/372997007/Crop600x400" title="2 Bedroom Apartment / flat to rent in Buffelsdrift AH - Pretoria" width="318"/>
</a>
</span>
<span class="p24_branding js_tilePseudoLink" data-href="/estate-agents/buysell/25994" data-target="" itemscope="" itemtype="http://schema.org/RealEstateAgent" title="Estate Agency profile for BUYSELL">
<img alt="BUYSELL" src="https://images.prop24.com/61814092/Ensure264x153"/>
<meta content="BUYSELL" itemprop="name"/>
<meta content="https://images.prop24.com/61814092/Ensure264x153" itemprop="image"/>
</span>
<a class="p24_content" href="/to-rent/buffelsdrift-ah/pretoria/gauteng/1/116872112">
<span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">
<span class="p24_price" content="8600" itemprop="price">
<meta content="ZAR" itemprop="priceCurrency"/>
                    R 8 600
                </span>
<span class="p24_title" itemprop="name">2 Bedroom Apartment</span>
<span class="p24_location">Buffelsdrift AH</span>
<span class="p24_excerpt" itemprop="description" title="2 Bedroom Apartment / flat to rent in Buffelsdrift AH - Pretoria">
                    This unit is on the 1st Floor of Oscars Place which is situated in the Paramount Estate Tygerpoort Pretoria East.  Easy access to ...
                </span>
</span>
<span class="clearfix"></span>
<span class="p24_icons">
<span class="p24_featureDetails" title="Bedrooms">
<svg height="20" width="20">
<image alt="Bedrooms" height="20" src="/Content/images/Optimized/Icons/icon_bed_new.svg?z=0bd7e1e97b09e85351e8" width="20" xlink:href="/Content/images/Optimized/Icons/icon_bed_new.svg?z=0bd7e1e97b09e85351e8"/>
</svg>
<span>2</span>
</span>
<span class="p24_featureDetails" title="Bathrooms">
<svg class="p24_bathroomIcon" height="20" width="20">
<image alt="Bathrooms" height="20" src="/Content/images/Optimized/Icons/icon_bath_new.svg?z=be0fb4c6f398267b865a" width="20" xlink:href="/Content/images/Optimized/Icons/icon_bath_new.svg?z=be0fb4c6f398267b865a"/>
</svg>
<span>2</span>
</span>
<span class="p24_featureDetails" title="Parking Spaces">
<svg class="p24_garageIcon" height="20" width="20">
<image alt="Parking Spaces" height="20" src="/Content/images/Optimized/Icons/icon_parking.svg?z=c9a3223daa656b51b425" width="20" xlink:href="/Content/images/Optimized/Icons/icon_parking.svg?z=c9a3223daa656b51b425"/>
</svg>
<span>1</span>
</span>
<span class="p24_favourite js_favourite" data-mandate-id="39434813" itemscope="" itemtype="http://schema.org/UserLikes">
<svg class="p24_favouriteToggle js_favouriteToggle hide" height="23" width="26">
<image height="23" src="/Content/images/Optimized/SPUI/spui_favourite_enabled.svg?z=9bc3b88817df6e396283" width="26" xlink:href="/Content/images/Optimized/SPUI/spui_favourite_enabled.svg?z=9bc3b88817df6e396283"/>
</svg>
<svg class="p24_favouriteToggle js_favouriteToggle" height="23" width="26">
<image height="23" src="/Content/images/Optimized/SPUI/spui_favourite_disabled.svg?z=232b4bf56db3ba880195" width="26" xlink:href="/Content/images/Optimized/SPUI/spui_favourite_disabled.svg?z=232b4bf56db3ba880195"/>
</svg>
</span> </span>
</a>
<span class="clearfix"></span>
</div>
</div>
</div>

In [ ]:
def clean_numeric(text, size = 1):
    """Helper to turn 'R 8 500' into 8500 or '80 m²' into 80."""
    size_multiplier = 1.0
    if not text: return None
    if 'ha' in text:
        num = text[:-3]
        try:
            num = float(num)
            return num * 10000
        except ValueError as e:
            print(f"error: {e}")
    
    if 'per' in text:
        size_multiplier = size if size else 1

    nums = re.sub(r'[^\d\.]', '', text)
    return float(nums) * size_multiplier if nums else None

def get_flags(description):
    desc = description.lower()
    return {
        "is_sharing" : 1 if any(x in desc for x in ['sharing', 'share']) else 0,
        "is_estate": 1 if "estate" in desc else 0,
        "has_garden": 1 if "garden" in desc else 0,
        "pet_friendly": 1 if "pet" in desc else 0,
        "is_modern": 1 if any(x in desc for x in ["modern", "newly", "renovated"]) else 0
    }

def get_property_type(text):
        """
        Feature engineering from title to get property type.
        """
        if text in ['Commercial Property', 'Industrial Property']:
            return text
        if 'Apartment' in text:
            return 'Apartment'
        if 'Townhouse' in text:
            return 'Townhouse'
        if 'House' in text:
            return 'House'
        return text

def extract_features(df_listings, suburb, city, munis):
    results = []
    for listing in df_listings.itertuples():
        soup = BeautifulSoup(listing.listing_data, "html.parser")

        # Property ID (from the link)
        link_tag = soup.find('a', href=True)
        prop_id = link_tag['href'].split('/')[-1].split('?')[0] if link_tag else None

        title_tag = soup.select_one(".p24_title")
        title = title_tag.text.strip() if title_tag else None

        prop_type = get_property_type(title) if title else None
        
        # 1. Basic Cleaning
        floor_size = clean_numeric(soup.select_one(".p24_size").text if soup.select_one(".p24_size") else None)
        price = clean_numeric(soup.select_one(".p24_price").text if soup.select_one(".p24_price") else None, floor_size)
        
        # 2. Icon Extraction
        features = {f.get('title', '').lower(): f.find('span').text.strip() 
                    for f in soup.find_all('span', class_='p24_featureDetails') if f.find('span')}

        # 3. Description & Flags
        description = soup.select_one(".p24_excerpt").text.strip() if soup.select_one(".p24_excerpt") else ""
        flags = get_flags(description)

        # 4. Assembly
        results.append({
            "property_id": prop_id,
            "price": price,
            "title": title,
            "type": prop_type,
            "suburb": suburb,
            "city": city,
            "municipality": munis,
            "bedrooms": clean_numeric(features.get("bedrooms")),
            "bathrooms": clean_numeric(features.get("bathrooms")),
            "parking": clean_numeric(features.get("parking spaces")),
            "floor_size": floor_size,
            **flags # Merges the dictionary of flags here
        })
    return results

test = extract_features(df, suburb, city, munis)

In [20]:
test

[{'property_id': '108782207',
  'price': 13200.0,
  'title': None,
  'suburb': 'heatherview',
  'city': 'akasia',
  'municipality': 'City of Tshwane',
  'bedrooms': 3.0,
  'bathrooms': 2.0,
  'parking': 2.0,
  'floor_size': 135.0,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116872499',
  'price': None,
  'title': '3 Bedroom House',
  'suburb': 'heatherview',
  'city': 'akasia',
  'municipality': 'City of Tshwane',
  'bedrooms': 3.0,
  'bathrooms': 2.0,
  'parking': 2.0,
  'floor_size': 2635.0,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116702498',
  'price': 7000.0,
  'title': '2 Bedroom House',
  'suburb': 'heatherview',
  'city': 'akasia',
  'municipality': 'City of Tshwane',
  'bedrooms': 2.0,
  'bathrooms': 1.0,
  'parking': 2.0,
  'floor_size': 300.0,
  'is_sharing': 0,
  'is_estate': 1,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 1},
 {'property_id': '116850269',
  'price': 5500.0,
  'title': 'Commercial Property',
  'suburb': 'heatherview',
  'city': 'akasia',
  'municipality': 'City of Tshwane',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 24.0,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116794164',
  'price': 5500.0,
  'title': '1 Bedroom Apartment',
  'suburb': 'heatherview',
  'city': 'akasia',
  'municipality': 'City of Tshwane',
  'bedrooms': 1.0,
  'bathrooms': 1.0,
  'parking': None,
  'floor_size': None,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 1,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '115999979',
  'price': 7000.0,
  'title': '2 Bedroom Apartment',
  'suburb': 'heatherview',
  'city': 'akasia',
  'municipality': 'City of Tshwane',
  'bedrooms': 2.0,
  'bathrooms': 2.0,
  'parking': 1.0,
  'floor_size': None,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116833744',
  'price': None,
  'title': '3 Bedroom House',
  'suburb': 'heatherview',
  'city': 'akasia',
  'municipality': 'City of Tshwane',
  'bedrooms': 3.0,
  'bathrooms': 2.0,
  'parking': 2.0,
  'floor_size': 2635.0,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116850243',
  'price': 5500.0,
  'title': 'Commercial Property',
  'suburb': 'heatherview',
  'city': 'akasia',
  'municipality': 'City of Tshwane',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 25.0,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116735719',
  'price': 7500.0,
  'title': '2 Bedroom Apartment',
  'suburb': 'heatherview',
  'city': 'akasia',
  'municipality': 'City of Tshwane',
  'bedrooms': 2.0,
  'bathrooms': 1.0,
  'parking': 1.0,
  'floor_size': None,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0}]

In [42]:
# print(clean_numeric("\n\r\n                    R 10\r\n                        per m²\n", 23994))
print(clean_numeric("2.5"))

2.5

In [44]:
lookup['municipality'].unique()

array(['City of Tshwane', 'Ekurhuleni', 'City of Johannesburg',
       'West Rand', 'Sedibeng'], dtype=object)

In [54]:
files = glob.glob("../data/1_bronze_raw/munis=sedibeng/city=*/type=rent/*.parquet")

In [56]:
files

['../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/3589_20260202_234225.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/17142_20260202_234308.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/3675_20260202_234334.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/16725_20260202_234424.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/3815_20260202_234454.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/17112_20260202_234524.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/3816_20260202_234554.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/17412_20260202_234653.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/3721_20260202_234719.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/3598_20260202_234746.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/12777_20260202_234830.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/3738_20260202_234858.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/3664_20260202_235023.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/17310_20260202_235111.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/3506_20260202_235135.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/10313_20260202_235202.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=evaton/type=rent/17545_20260202_235242.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/17317_20260203_071333.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3692_20260203_071400.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3693_20260203_071458.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3695_20260203_071530.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3812_20260203_071605.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3696_20260203_071630.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3811_20260203_071653.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3706_20260203_071736.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3707_20260203_071801.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/10443_20260203_071833.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3801_20260203_071910.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3710_20260203_071951.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/15666_20260203_072012.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3802_20260203_072040.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/10477_20260203_072422.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3717_20260203_072509.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/18145_20260203_072552.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3530_20260203_072620.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3799_20260203_072654.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3725_20260203_072719.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/17813_20260203_072744.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3800_20260203_072811.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3731_20260203_073023.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/17240_20260203_073052.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/16729_20260203_073121.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3793_20260203_073232.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3796_20260203_073307.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/17924_20260203_073409.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/17242_20260203_073457.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3732_20260203_073547.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3733_20260203_073634.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/17814_20260203_073710.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3785_20260203_073741.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3677_20260203_073806.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3737_20260203_073835.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/10563_20260203_073900.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/17550_20260203_073928.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3743_20260203_073956.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3682_20260203_074023.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3744_20260203_074131.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3813_20260203_074200.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3795_20260203_074455.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3798_20260203_074534.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3807_20260203_074600.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/17308_20260203_074628.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/12115_20260203_074656.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3808_20260203_074722.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/16642_20260203_074818.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3772_20260203_074850.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3773_20260203_074917.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/17279_20260203_074944.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/10510_20260203_075008.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=meyerton/type=rent/3777_20260203_075049.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3667_20260206_044758.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/17255_20260206_044827.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/17191_20260206_044851.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/17213_20260206_044921.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/17233_20260206_045002.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/17504_20260206_045032.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3616_20260206_045059.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/25573_20260206_045123.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/17336_20260206_045158.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/25571_20260206_045221.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3835_20260206_045245.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3836_20260206_045326.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3837_20260206_045351.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3838_20260206_045416.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3839_20260206_045441.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3841_20260206_045503.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3842_20260206_045529.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/16946_20260206_045559.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/16945_20260206_045626.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3844_20260206_045654.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3847_20260206_045726.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3848_20260206_045759.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3849_20260206_045831.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3683_20260206_045854.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=sebokeng/type=rent/3826_20260206_045919.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vaal_marina/type=rent/3760_20260206_074515.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3587_20260206_075111.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3590_20260206_075137.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3591_20260206_075202.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3592_20260206_075226.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/16061_20260206_075302.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/17144_20260206_075353.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3593_20260206_075427.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/13858_20260206_075457.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3594_20260206_075604.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3595_20260206_075643.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3665_20260206_075706.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/17225_20260206_075730.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3596_20260206_075759.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/17124_20260206_075842.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/17125_20260206_075919.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3599_20260206_075943.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3600_20260206_080015.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/17192_20260206_080044.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3604_20260206_080113.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3605_20260206_080144.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3607_20260206_080207.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3608_20260206_080244.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3609_20260206_080323.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3611_20260206_080350.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3612_20260206_080431.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3613_20260206_080511.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3614_20260206_080539.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/32739_20260206_080615.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3617_20260206_080642.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3618_20260206_080720.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3619_20260206_080755.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3620_20260206_080824.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3622_20260206_080850.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/17346_20260206_080921.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3586_20260206_080957.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3625_20260206_081024.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3626_20260206_081101.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/17358_20260206_081141.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3627_20260206_081207.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3628_20260206_081236.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3629_20260206_081517.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3577_20260206_081616.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3632_20260206_082201.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3578_20260206_082257.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3579_20260206_082856.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3580_20260206_082922.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/16789_20260206_082948.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3581_20260206_083037.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3582_20260206_083740.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3659_20260206_084222.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3660_20260206_084246.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3662_20260206_084308.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vanderbijlpark/type=rent/3663_20260206_084337.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/12192_20260206_084408.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/17154_20260206_084428.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3688_20260206_084459.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3689_20260206_084638.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3691_20260206_084706.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/17162_20260206_084803.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3697_20260206_084825.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3576_20260206_084852.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3698_20260206_084954.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3699_20260206_085018.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3701_20260206_085111.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3705_20260206_085223.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/15668_20260206_085303.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3711_20260206_085329.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3714_20260206_085357.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3718_20260206_085424.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3720_20260206_085449.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3723_20260206_085524.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3729_20260206_085549.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/33202_20260206_085616.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3730_20260206_085643.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3739_20260206_085707.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/17379_20260206_085752.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3740_20260206_085816.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/15129_20260206_085848.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3745_20260206_090100.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/17362_20260206_090124.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3671_20260206_090149.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3672_20260206_090213.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3670_20260206_090243.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3746_20260206_090311.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3747_20260206_090408.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3749_20260206_090436.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3750_20260206_090504.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3754_20260206_090553.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3781_20260206_091118.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/17360_20260206_091227.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3782_20260206_091255.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3762_20260206_091417.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3763_20260206_091444.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3764_20260206_091514.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/16735_20260206_091542.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/17247_20260206_091744.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/16792_20260206_091816.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/33575_20260206_091844.parquet',
 '../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent/3774_20260206_091912.parquet']

In [34]:
folder_path = "../data/1_bronze_raw/munis=sedibeng/city=vereeniging/type=rent"
file_name = "3701_20260206_085111.parquet"
file_path = os.path.join(folder_path, file_name)

df = pd.read_parquet(file_path)
suburb_id = file_name.split('_')[0]
suburb, city, munis = lookup.loc[lookup['suburb_id'] == suburb_id, ['suburb_name', 'city_name', 'municipality']].values[0]

test_2 = extract_features(df, suburb, city, munis)

In [24]:
text = df.loc[df['listing_number']=='116858222', 'listing_data'].values[0]
soup_t = BeautifulSoup(text)
soup_t.select_one(".p24_price").text

'\n\r\n                    R 10\r\n                        per m²\n'

In [35]:
test_2

[{'property_id': '116859704',
  'price': 10900,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': 3,
  'bathrooms': 2,
  'parking': 2,
  'floor_size': None,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116298038',
  'price': 1308090,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 37374,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116778508',
  'price': 1225000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 35000,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116872606',
  'price': 13000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': 2,
  'bathrooms': 15,
  'parking': 3,
  'floor_size': 366,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 1},
 {'property_id': '115330063',
  'price': 255360,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 7296,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '114501995',
  'price': 1308090,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 37374,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '114501783',
  'price': 869330,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 24838,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116871457',
  'price': 11800,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': 4,
  'bathrooms': 2,
  'parking': None,
  'floor_size': 2181,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116693317',
  'price': None,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 2390,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116756695',
  'price': 140000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 4000,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '110357139',
  'price': 4650,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': 1,
  'bathrooms': 1,
  'parking': 1,
  'floor_size': 60,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116858195',
  'price': 31500,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 700,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116858230',
  'price': 108675,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 3105,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116858225',
  'price': 98140,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 2804,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116839949',
  'price': 35700,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 1020,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116858200',
  'price': 18000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 400,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116839204',
  'price': 140000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 4000,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116800411',
  'price': 10000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': 3,
  'bathrooms': 15,
  'parking': 1,
  'floor_size': 1011,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '109279259',
  'price': 11500,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 300,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116873570',
  'price': 300000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 30000,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116819787',
  'price': 11000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': 2,
  'bathrooms': 2,
  'parking': 2,
  'floor_size': None,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 1},
 {'property_id': '116802827',
  'price': 6000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': 1,
  'bathrooms': 15,
  'parking': 2,
  'floor_size': None,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 1,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '110391069',
  'price': 195000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 6500,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116426754',
  'price': 350000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 10000,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116426710',
  'price': 143500,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 4100,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116858222',
  'price': 20000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 2000,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116858217',
  'price': 20000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 2000,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116777859',
  'price': 6780,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': 1,
  'bathrooms': 1,
  'parking': 1,
  'floor_size': 29000.0,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 1,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116371591',
  'price': 350000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 10000,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '112511905',
  'price': 9200,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 225,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116371819',
  'price': 280000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 8000,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116726748',
  'price': 9200,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 225,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116116843',
  'price': 16200,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 190,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116022900',
  'price': 3850,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': 1,
  'bathrooms': 1,
  'parking': None,
  'floor_size': None,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 1},
 {'property_id': '116703451',
  'price': 143500,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 4100,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116712431',
  'price': None,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 6000,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116712417',
  'price': None,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 30000,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116669934',
  'price': 142830,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 2248,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116705225',
  'price': 6700,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': 2,
  'bathrooms': 1,
  'parking': 1,
  'floor_size': None,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116858219',
  'price': 59500,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 1700,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116858218',
  'price': 47250,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 1350,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '114501548',
  'price': 349860,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 9996,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116583879',
  'price': 9200,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 225,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '110308937',
  'price': 8500,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 166,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116290655',
  'price': 234500,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 6700,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '114642813',
  'price': 59500,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 1700,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116731443',
  'price': 9200,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 225,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116652905',
  'price': 7000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': 2,
  'bathrooms': 1,
  'parking': 1,
  'floor_size': 1388,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116748033',
  'price': 9200,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 225,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '113967257',
  'price': 17000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 600,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116552080',
  'price': 22000,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': None,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '113804061',
  'price': 94500,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 2700,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116585243',
  'price': 9200,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 225,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116117276',
  'price': 18445,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 270,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '116371728',
  'price': 74160,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 824,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '110000421',
  'price': 9200,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 225,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0},
 {'property_id': '108052911',
  'price': 12075,
  'suburb': 'duncanville',
  'city': 'vereeniging',
  'municipality': 'Sedibeng',
  'bedrooms': None,
  'bathrooms': None,
  'parking': None,
  'floor_size': 300,
  'is_sharing': 0,
  'is_estate': 0,
  'has_garden': 0,
  'pet_friendly': 0,
  'is_modern': 0}]